импортируем необходимые библиотеки

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

импортируем все доступные нам данные

In [11]:
events_df = pd.read_csv('data/Retailrocket_Dataset/events.csv')
ip_part_1_df = pd.read_csv('data/Retailrocket_Dataset/item_properties_part1.csv')
ip_part_2_df = pd.read_csv('data/Retailrocket_Dataset/item_properties_part2.csv')
ct_df = pd.read_csv('data/Retailrocket_Dataset/category_tree.csv')

объединяем item_properties в один датафрейм

In [12]:
ip_df = pd.concat([ip_part_1_df, ip_part_2_df], ignore_index=True)

посмотрим на первые строчки датафрейма _ip_df_

In [17]:
ip_df.head()

       timestamp  itemid    property                            value
0  1435460400000  460429  categoryid                             1338
1  1441508400000  206783         888          1116713 960601 n277.200
2  1439089200000  395014         400  n552.000 639502 n720.000 424566
3  1431226800000   59481         790                       n15360.000
4  1431831600000  156781         917                           828513

посмотрим на метаданные датафрейма _ip_df_

In [16]:
ip_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20275902 entries, 0 to 20275901
Data columns (total 4 columns):
 #   Column     Dtype
---  ------     -----
 0   timestamp  int64
 1   itemid     int64
 2   property   object
 3   value      object
dtypes: int64(2), object(2)
memory usage: 618.8+ MB

посчитаем количество дубликатов в датафрейме _ip_df_

In [14]:
ip_df.duplicated().sum()

np.int64(0)

проверим количество пропущенных значений в датафрейме _ip_df_

In [36]:
ip_df.isnull().sum()

timestamp    0
itemid       0
property     0
value        0
dtype: int64

посмотрим на количество уникальных значений переменных _property_, _value_ и _itemid_

In [42]:
print(f'количество уникальных значений переменной property: {ip_df['property'].nunique()}')
print(f'количество уникальных значений переменной itemid: {ip_df['itemid'].nunique()}')
print(f'количество уникальных значений переменной value: {ip_df['value'].nunique()}')
print(f'общее количество наблюдений: {ip_df.shape[0]}')

количество уникальных значений переменной property: 1104
количество уникальных значений переменной itemid: 417053
количество уникальных значений переменной value: 1966868
общее количество наблюдений: 20275902

пока сходу непонятно, как работать с этим датафреймом (возможно много чего окажется бесполезным), поэтому есть идея оставить только строчки где property == 'categoryid' и/или 'available' (бизнес-метрики как считать?)

In [67]:
ip_df[ip_df.property == 'categoryid']

              timestamp  itemid    property value
0         1435460400000  460429  categoryid  1338
140       1432436400000  281245  categoryid  1277
151       1435460400000   35575  categoryid  1059
189       1437274800000    8313  categoryid  1147
197       1437879600000   55102  categoryid    47
...                 ...     ...         ...   ...
20275797  1433646000000  255696  categoryid  1404
20275822  1431226800000  390760  categoryid   324
20275830  1437879600000  211844  categoryid   256
20275872  1435460400000  444741  categoryid   511
20275878  1435460400000   97513  categoryid  1385

[788214 rows x 4 columns]

In [66]:
ip_df[ip_df.property == 'available']

              timestamp  itemid   property value
5         1436065200000  285026  available     0
15        1437274800000  186518  available     0
79        1433646000000  423682  available     0
82        1434250800000  316253  available     1
96        1437274800000  430459  available     0
...                 ...     ...        ...   ...
20275845  1440903600000  229797  available     0
20275855  1438484400000  225378  available     1
20275889  1433041200000  356167  available     0
20275891  1439089200000  200211  available     0
20275896  1436065200000   74745  available     0

[1503639 rows x 4 columns]

---

In [34]:
events_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2756101 entries, 0 to 2756100
Data columns (total 5 columns):
 #   Column         Dtype
---  ------         -----
 0   timestamp      int64
 1   visitorid      int64
 2   event          object
 3   itemid         int64
 4   transactionid  float64
dtypes: float64(1), int64(3), object(1)
memory usage: 105.1+ MB

In [28]:
events_df.duplicated().sum()

np.int64(460)

In [35]:
ct_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1669 entries, 0 to 1668
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   categoryid  1669 non-null   int64
 1   parentid    1644 non-null   float64
dtypes: float64(1), int64(1)
memory usage: 26.2 KB

In [29]:
ct_df.duplicated().sum()

np.int64(0)

In [33]:
events_df[events_df.duplicated()]

             timestamp  visitorid      event  itemid  transactionid
22404    1433180781440    1045411  addtocart  379647            NaN
34465    1433274223925     366538  addtocart  252068            NaN
39738    1433265100661     198153  addtocart   48715            NaN
41774    1433270868154    1268755       view   60980            NaN
42469    1433277134682     555487  addtocart  397642            NaN
...                ...        ...        ...     ...            ...
2748964  1438346018813     722488       view   97303            NaN
2750464  1438370523152     896869  addtocart   85004            NaN
2752725  1438405570135     708442  addtocart  392883            NaN
2753763  1438376127329     372829  addtocart  388276            NaN
2755356  1438378507708     415611  addtocart  177728            NaN

[460 rows x 5 columns]

In [47]:
events_df.event.value_counts()

event
view           2664312
addtocart        69332
transaction      22457
Name: count, dtype: int64

In [52]:
events_df[events_df.duplicated()]

             timestamp  visitorid event  itemid  transactionid
1        1433224214164     992329  view  248676            NaN
2        1433221999827     111016  view  318965            NaN
3        1433221955914     483717  view  253185            NaN
4        1433221337106     951259  view  367447            NaN
5        1433224086234     972639  view   22556            NaN
...                ...        ...   ...     ...            ...
2756096  1438398785939     591435  view  261427            NaN
2756097  1438399813142     762376  view  115946            NaN
2756098  1438397820527    1251746  view   78144            NaN
2756099  1438398530703    1184451  view  283392            NaN
2756100  1438400163914     199536  view  152913            NaN

[2756099 rows x 5 columns]